### ISSUE TITLE
jai skid quoi?

### ISSUE THREAD

**Issue by billythegoat356** [Its-Vichy/lets-talk-about-discord#5]
1: jai skid quoi? donne une preuve, et mon share bot tape 2k partages par seconde, ceux sur github a peine une centaine...
2: je scam pas, cest moi qui la dev le sharebot donc 100% legit
3: dans toutes les communautés ya des débutants. je prefere avoir une grosse commu avec des debutants, quune petite commu de 20 personnes qui savent que spam "issou".

J'attends une réponse de ta part, me veski pas comme d'habitude ;)

**Comment by Its-Vichy** [comment]
Whow mec, t'a appris à mettre des thread !, qui se ressemble s'assemble t'a une commu de teubé ! Moi j'ai pas de temps à perdre avec des autiste, je fait mon bussiness je suis pas prof de programmation. Mon public est celui que je recherche, pas des gosses de 13ans qui ne savent pas utiliser un pc.

Ensuite tu revend ta vielle src skid et tu te sent plus car t'a mis des threads, bouge toi le cul et fait le en golang ou dans un language plus rapide, mais bon tu ne sait même pas comment fonctionne l'api que tu as copy/past sur github. Il va y avoir encore tous tes membres chialer quand ton bot se seras fait patch :, et que tu ne seras pas capable de le mettre à jour par toi même.

Ton level en prog et éclaté, pour moi t'a ta place dans les "skid" d'internet voilà tous :p, ton avis j'en m'en contre balance,
Sans moi tu ne serais pas la car oui ?, c'est qui qui t'a fais rentrer dans tous ça ?, c'est moi,

Tu t'es permit de copier tous ce que j'ai fait sur tiktok à mes début et tes grand tallent de suceur ont fait que les skid te collent au gland :)

Donc par logique les gens t'aime bien car tu est h24 a leurs expliquer comment faire si, comment faire ça. En réalité si tu aide tous le monde, ils ne sauront jamais comment se débrouiller par eux même, c'est ça qui fait que 95% de la commu française sur discord et COMPLETEMENT AUTISTE; J'en ai clairement honte, à par des rebeux qui font "au chui un carder" "j'ai apris a utiliser open bullet" "je dev en python des tool de DDoS", et tous les jean-kevin qui savent que copy/past, il reste très peux de gens talentueux.

T'étais bien content quand j'tai appris à reverse un webhook ?, Quand je t'ai montrer en quoi ton code étais pourris tu ne savait pas même faire une boucle.

Enfin bref, retourne faire tes tiktok et t'attirer des suceurs de queue et les sucer pour avoir ce que tu veux contre ton "share bot" :,
J'ai pas de temps à perdre avec toi tu en vaux aucunement la peine

**Comment by billythegoat356** [comment]
pas ouf de close.
non tu ne m'as rien appris, je ne t'ai jamais copié. créer un tiktok n'est pas copier. et non c'est pas que créer des threads que j'ai amélioré, utilise ton cerveau celui sur github crée déjà des threads. 
bref tu m'as montré que tu n'as aucun argument.
reste avec ta commu de 12 personnes, m'en branle de toi. personne t'aime sur discord.
donc dis moi ce que j'ai skid. je le redis: faire le meme concept de programme c'est skid d'après toi? 😂
et oui mon niveau en prog est si éclaté que chaque fois qu'on partait en coc je gagnais. bien sur c'est toi qui m'a tout appris!
je faisais de l'info et du dev bien avant de te rencontrer. arrête d'essayer de t approprier mon "succès" mdr c'est ridicule
et on s'en fout que j'aie une commu d'autistes à 95%, ca change rien ça reste une commu.
ducoup je le redis encore et encore et encore.
je vends un share bot, même si on peut en avoir gratuitement sur internet.
j'ai rien skid, le mien est mieux et plus rapide.
t'as aucun argument ni de preuve, c'est pathétique.
et tkt pas que je sais faire des requêtes en python mdrr

**Comment by Its-Vichy** [comment]
"pas ouf de close.", le sujet est clos, ça t'empêche pas de répondre donc tg?

" je ne t'ai jamais copié",
- Channel telegram
- Sujet video tiktok
- Readme
- etc

"celui sur github crée déjà des threads."
Peux-être que c'est un bouffon qui l'a poster et que par hasard, t'a juste a optimiser et utiliser des lib plus rapide tel que jsp moi AIOHTTP :p 

"bref tu m'as montré que tu n'as aucun argument."
Je suis pas la pour argumenter, simplement pour dire des fait, j'en ai rien à foutre de ce que tu peux penser

"reste avec ta commu de 12 personnes"
Ma commu de 12 personnes me suffit largement, je suis pas la pour avoir 10k suceurs

""m'en branle de toi. personne t'aime sur discord.""
Je suis pas la pour me faire aimer, & dans ce cas pourquoi tu est sur ce repo si tu t'en blc ?

"je faisais de l'info et du dev bien avant de te rencontrer."
Tu as apris à faire un print ?, car c'étais ton niveaux

"chaque fois qu'on partait en coc je gagnais"
Je fais pas de COC avec des gens, c'est difficile d'en avoir fait avec toi

"j'ai rien skid, le mien est mieux et plus rapide."
J'ai pas voler la recette du pain perdu, le mien est meilleur ?, aucun sens bouffon

"et tkt pas que je sais faire des requêtes en python mdrr"
Non dis wllh ?, personne le sait

**Comment by loTus04** [comment]
créé un channel telegram = te copié ??
t'es pas au centre du monde vichy

**Comment by AbdullahC667** [comment]
> am = te copié ??
bah un peu genre il reproduit les meme action que lui , crée un canal juste apres que vichy la fait

**Comment by billythegoat356** [comment]
je t'ai copié tiktok? mdrrr tu faisais des tiktoks sur "les femmes à la cuisine", je présentais mes programmes. et sache que j'ai eu tiktok et j'en faisais bien avant toi.
j'ai crée un telegram pour pas sauter sur discord... et je ne poste rien dedans. wow je t'ai copié!
et je t'ai également copié en faisant des readme sur github! mdrrrr
ensuite tu ne m'as toujours pas répondu: qu'est ce que jai skid?
tu fais que contourner la question parce que tu n'as aucune réponse, tu te crois juste intéressant à dire que je skid alors que c'est faux.
aucun rapport avec le pain perdu. je sais pas ce que tu racontes... tu te ridiculises, comme d'hab.
je te le dit encore une fois, j'attends ta réponse, ce que j'ai skid. parce que faire le meme concept de programme, mais la tui 100% différente et 10fois plus rapide ne veut pas dire skid.

**Comment by Its-Vichy** [comment]
"aucun rapport avec le pain perdu", ton cerveaux est trop petit pour faire une comparaison ?

**Comment by billythegoat356** [comment]
ducoup au lieu dattaquer sur des choses qui nont aucun rapport tu peux me répondre ce que jai skid?

**Comment by billythegoat356** [comment]
tu fais que esquiver la question :)

**Comment by Its-Vichy** [comment]
ta race, apprend à lire non ?

**Comment by Vodkarm** [comment]
pourquoi parler ici? parlez en mp ça ira plus vite 👀

**Comment by Its-Vichy** [comment]
On t'a rien demander ?

**Comment by billythegoat356** [comment]
"on ta rien demander" apprends a conjuguer un verbe avant de parler de mon cerveau vichy. et tu ne mas toujours pas donné de preuves que je skid :)
"Peux-être que c'est un bouffon qui l'a poster et que par hasard, t'a juste a optimiser et utiliser des lib plus rapide tel que jsp moi AIOHTTP :p"
cest une preuve ca? cest juste une supposition et je sais tres bien faire des requetes tinquiete pas, jai pas besoin de skid.

ducoup jattends tes preuves :)

**Comment by billythegoat356** [comment]
apres si ten as pas cest pas grave, tout le monde le sait que tes une sous merde qui se cherche des amis.

**Comment by Its-Vichy** [comment]
Tous est [la](https://www.youtube.com/watch?v=QDia3e12czc)

**Comment by Mewzax** [comment]
Mdr

> Tous est [la](https://www.youtube.com/watch?v=QDia3e12czc)

**Comment by billythegoat356** [comment]
tellement drole, on est morts de rire

**Comment by Its-Vichy** [comment]
ça prend le seum

**Comment by billythegoat356** [comment]
ah oui clairement,
