### ISSUE TITLE
Social404 - dirt

### ISSUE THREAD

**Issue by 63o** [Its-Vichy/lets-talk-about-discord#9]
lmao, social404. big skid, i  stole his acc and nuked his servers and had him begging me to give it back, and then tried to pay me to grab people. i rejected his offer, so he got mad and started claiming to be a hacker, but dodged every skid quiz . there is much more than this - i just think its very funny

**Comment by Its-Vichy** [comment]
this indian tried to paid me for dev many tools and resell them lol
